### ISSUE TITLE
Replace babel-preset-es2015

### ISSUE THREAD

**Issue by nasyrov** [bem/bem-react-core#138]
Hi guys,

Any plans to replace `babel-preset-es2015` with `babel-preset-env`?
See https://github.com/babel/babel-preset-env#babel-preset-env----

Cheers,
E

**Comment by veged** [comment]
We can't just start to use `babel-preset-env` since every user has own configs for supported platforms, but we need to publish already compiled version. So even if we start to use `babel-preset-env` it doesn't allow every user to have own config.

But you already can just install `bem-react-core` from git-repo (sources) and configure any build configs you want (even with `babel-preset-es2015`).
