### ISSUE TITLE
Add an ability to pass mix to Block/Elem via props

### ISSUE THREAD

**Issue by DavyJohnes** [bem/bem-react-core#305]
So we can use BEM entities in this way:
```js
class MyBlock extends Block {
    block = 'MyBlock';
}

class AnotherBlock extends Block {
    block = 'AnotherBlock';

    content() {
        return <MyBlock mix={block: 'Block1', elem: 'Elem1'} />;
    }
}
```

**Comment by awinogradov** [comment]
Sorry, but it's impossible. `mix` prop available only for `Bem` component. But it'll be removed soon #300.  So, we support `className` only as result API for `Block`/`Elem`, because it's a simple React component and public API doesn't know anything about BEM.

For using BEM classes in `className` we added a simple  helper.

``` ts
import { Block } from 'bem-react-core';

class Button extends Block {
  block = 'Button';

  content() {
    return (
      <span className={this.bemClassName('inner', { show: 'me' })}>{this.props.text}</span>
    );
  }
}
```

We'll add it to docs soon, sorry for delay and thanks for your report!
